import { Chapter, TaskId } from './types';

const createEmptyTasks = (): Record<TaskId, boolean> => ({
  lectures: false,
  notes: false,
  short_notes: false,
  dpps: false,
  ncert_exam: false,
  ncert_exer: false,
  ncert_exen: false,
  revision: false,
  reattempt_imp_q: false,
  qcb: false,
  pyqs: false,
});

const generateChapters = (prefix: string, names: string[]): Chapter[] => {
  return names.map((name, i) => ({
    id: `${prefix}-${i + 1}`,
    name,
    tasks: createEmptyTasks(),
    revisions: [false, false, false, false, false, false, false],
    reattempts: [false, false],
  }));
};

export const INITIAL_STATE = {
  physics: generateChapters('phy', [
    'Electric Charges and Fields',
    'Electrostatic Potential and Capacitance',
    'Current Electricity',
    'Moving Charges and Magnetism',
    'Magnetism and Matter',
    'Electromagnetic Induction',
    'Alternating Current',
    'Electromagnetic Waves',
    'Ray Optics and Optical Instruments',
    'Wave Optics',
    'Dual Nature of Radiation and Matter',
    'Atoms',
    'Nuclei',
    'Semiconductor Electronics',
  ]),
  chemistry: generateChapters('chem', [
    'Solutions',
    'Electrochemistry',
    'Chemical Kinetics',
    'd and f Block Elements',
    'Coordination Compounds',
    'Haloalkanes and Haloarenes',
    'Alcohols, Phenols and Ethers',
    'Aldehydes, Ketones and Carboxylic Acids',
    'Amines',
    'Biomolecules',
  ]),
  math: generateChapters('math', [
    'Relations and Functions',
    'Inverse Trigonometric Functions',
    'Matrices',
    'Determinants',
    'Continuity and Differentiability',
    'Application of Derivatives',
    'Integrals',
    'Application of Integrals',
    'Differential Equations',
    'Vector Algebra',
    'Three Dimensional Geometry',
    'Linear Programming',
    'Probability',
  ]),
  english: generateChapters('eng', [
    'The Last Lesson',
    'Lost Spring',
    'Deep Water',
    'The Rattrap',
    'Indigo',
    'Poets and Pancakes',
    'The Interview',
    'Going Places',
    'My Mother at Sixty-six',
    'Keeping Quiet',
    'A Thing of Beauty',
    'A Roadside Stand',
    "Aunt Jennifer's Tigers",
    'The Third Level',
    'The Tiger King',
    'Journey to the end of the Earth',
    'The Enemy',
    'On the Face of It',
    'Memories of Childhood',
    'Notice',
    'Formal/Informal Invitation and Reply',
    'Letter to Editor/Application for Job',
    'Article Writing',
    'Report Writing',
    'Reading Comprehension'
  ]),
  pe: generateChapters('pe', [
    'Management of Sporting Events',
    'Children and Women in Sports',
    'Yoga as Preventive measure for Lifestyle Disease',
    'Physical Education and Sports for CWSN',
    'Sports and Nutrition',
    'Test and Measurement in Sports',
    'Physiology and Injuries in Sports',
    'Biomechanics and Sports',
    'Psychology and Sports',
    'Training in Sports'
  ]),
};
